# Generated by Django 6.0.2 on 2026-02-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(verbose_name=20)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
