# Generated by Django 6.0.2 on 2026-02-26 13:10

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_client_address_alter_client_c_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='case_description',
            field=models.TextField(blank=True, null=True, default='No description'),
        ),
        migrations.AddField(
            model_name='client',
            name='case_type',
            field=models.CharField(max_length=100, default='Civil'),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=50, default='Surat'),
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='client',
            name='dob',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='opposite_party',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(max_length=50, default='Gujarat'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='identity_proof',
            field=models.ImageField(upload_to='client_ids/', null=True, blank=True),
        ),
    ]