# Generated by Django 6.0.2 on 2026-02-27 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_client_c_name_alter_client_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocate',
            name='notes',
        ),
    ]
